spring:
  application:
    name: pizzeria

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

#activar logs de spring security
logging:
  level:
    com.example.pizzeria: DEBUG        # tus clases → ves todo (INFO + WARN + ERROR + DEBUG)
    org.springframework.security: WARN # Spring Security → solo warnings, menos ruido
    org.springframework.web: WARN
