spring:
  application:
    name: pizzeria

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

#activar logs de spring security
logging:
  level:
    org.springframework.security: DEBUG
